image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pyenv install 3.10.11 || true
      pyenv local 3.10.11
      pip install --upgrade pip
      pip install -r requirements.txt
    command: python manage.py runserver 0.0.0.0:8000

ports:
  - port: 8000
    onOpen: open-preview
