# Generated by Django 3.2.4 on 2023-04-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggydanger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggydanger',
            name='bites_babies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doggydanger',
            name='bites_bono',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doggydanger',
            name='bites_burglars',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doggydanger',
            name='bites_kids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doggydanger',
            name='bites_teenagers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doggydanger',
            name='dangerously_cute',
            field=models.TextField(blank=True),
        ),
    ]
