# Generated by Django 3.2.4 on 2023-04-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggydanger', '0005_alter_doggydanger_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggydanger',
            name='bites_bush',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doggydanger',
            name='bites_reagan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doggydanger',
            name='bites_thatcher',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doggydanger',
            name='bites_trump',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doggydanger',
            name='bites_wbush',
            field=models.TextField(blank=True),
        ),
    ]
