# Generated by Django 3.2.4 on 2023-04-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogdanger', '0002_auto_20230421_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogdanger',
            options={'ordering': ['-created_at']},
        ),
    ]
