# Generated by Django 3.2.4 on 2023-04-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogdanger', '0003_alter_dogdanger_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogdanger',
            old_name='bites_bono',
            new_name='bites_bolsonaro',
        ),
    ]
