# Generated by Django 3.2.4 on 2023-05-10 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vet_name', models.CharField(blank=True, max_length=255)),
                ('vet_phone', models.CharField(blank=True, max_length=255)),
                ('vet_email', models.CharField(blank=True, max_length=255)),
                ('chipped', models.CharField(blank=True, max_length=255)),
                ('kennel_cough', models.CharField(blank=True, max_length=255)),
                ('rabies', models.CharField(blank=True, max_length=255)),
                ('allergies', models.CharField(blank=True, max_length=255)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'vet_name')},
            },
        ),
    ]
