# Generated by Django 3.2.4 on 2023-04-19 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doghealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doghealth',
            unique_together={('owner', 'vet_name')},
        ),
    ]
