# Generated by Django 3.2.4 on 2023-05-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_name',
            field=models.TextField(blank=True),
        ),
    ]
