# Generated by Django 3.2.4 on 2023-04-19 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dogprofile',
            unique_together={('owner', 'dog_name')},
        ),
    ]
