# Generated by Django 3.2.4 on 2023-04-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogprofiles', '0002_alter_dogprofile_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogprofile',
            old_name='dog_image',
            new_name='dog_profile_image',
        ),
    ]
