# Generated by Django 3.2.4 on 2023-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogprofiles', '0002_alter_dogprofile_dog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_name',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
