# Generated by Django 3.2.4 on 2023-04-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogprofiles', '0003_rename_dog_image_dogprofile_dog_profile_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dogprofile',
            unique_together=set(),
        ),
    ]
