# Generated by Django 3.2.4 on 2023-04-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogprofiles', '0004_alter_dogprofile_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogprofile',
            name='dog_profile_image',
        ),
    ]
