# Generated by Django 3.2.4 on 2023-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogprofiles', '0005_remove_dogprofile_dog_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogprofile',
            name='dog_profile_image',
            field=models.ImageField(default='../default_profile_qdjgyp', upload_to='images/'),
        ),
    ]
