# Generated by Django 3.2.4 on 2023-04-23 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogprofiles', '0006_dogprofile_dog_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_profile_image',
            field=models.ImageField(default='../default_dog-profile_gtehul.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
