# Generated by Django 3.2.4 on 2023-04-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogprofiles', '0008_alter_dogprofile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_profile_image',
            field=models.ImageField(blank=True, default='../default_dog-profile_gtehul.png', upload_to='images/'),
        ),
    ]
