# Generated by Django 3.2.4 on 2023-05-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogprofiles', '0009_alter_dogprofile_dog_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_age',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dogprofile',
            name='dog_color',
            field=models.TextField(blank=True),
        ),
    ]
